### PR TITLE
Broker queue.

### PR DESCRIPTION
**Pull request by jmalloc**
The queue is the list of messages that need to be brokered. 

The broker consumes from the queue, and then dispatches messages to the specific replicas that handle each route.

### CODE REVIEW

**Comment by jmalloc** [comment]
This is still a draft, but would appreciate feedback about how much sense it makes, especially docs, as I go.

**Comment by koden-km** [comment]
It looks good. Just the spelling of `acnowledging`. The api makes sense. Should I submit a review result for this draft?

**Comment by jmalloc** [comment]
Nah, I'll add more over time, I just feel like I need a bit more back and forth with this broker stuff as it's taking me a while to get a clear picture of what to actually *do*.

**Comment by jmalloc** [comment]
This needs a few more tests yet, but I believe the implementation is complete.

**Pull request merged**
